### ISSUE TITLE
Actually show real errors instead of the default sinatra ones

### ISSUE THREAD

**Issue by naomiEve** [dangeru/awoo#25]
As referenced in issue https://github.com/dangeru/awoo/issues/24 all invalid API calls throw a regular Sinatra error, should we display a nicely formatted JSON one for them i.e.  `{"404": "Thread not found"}`, or just leave the standard?

**Comment by nilesr** [comment]
It'll be easier for people to check the response code of the HTTP request then to bounce back a 200 OK and let the end user figure out why there's no `"content"` key in the json object.

**Comment by naomiEve** [comment]
we can send both 404 and the json error code

**Comment by naomiEve** [comment]
i think it actually sends a 500 error now, not 404

**Comment by sugoiuguu** [comment]
somehow there's a thread without title, which was fucking with my python client, thought it was my fault, it's you guys' lol, check this page https://dangeru.us/tech/thread/31574

**Comment by sugoiuguu** [comment]
also there are a couple of posts without content as well

**Comment by naomiEve** [comment]
we don't check if the post has no title, so it passes
we might as well later fix it

**Comment by sugoiuguu** [comment]
![](https://u.sicp.me/kwaVs.png)
Looks like a regular post ended up on the thread list from the tech board.
Reproducible with `$ curl https://dangeru.us/api/v2/board/tech`.

**Comment by nilesr** [comment]
I asked prefetcher if we should make sure there's something in the title box and he told me not to worry about it. If you enable userscript you can press the "+1" text to get to the thread

**Comment by naomiEve** [comment]
huh, the post isn't even on "tech" as suggested by this thread `https://dangeru.us/u/thread/30955`
![obraz](https://user-images.githubusercontent.com/9293619/30607616-ed091d54-9d75-11e7-9b97-53b3a1b4e62a.png)

**Comment by sugoiuguu** [comment]
do you guys have a discord or some place I can hang out? wouldn't mind helping from time to time, I got some time to kill when I get home from classes and shit

**Comment by naomiEve** [comment]
we do have the official danger/u/ discord over at https://discord.gg/truKDM

**Comment by naomiEve** [comment]
fixed in commit https://github.com/dangeru/awoo/commit/70114dbfa6fb9fe900026a82f537739491bf7a5c, incorrect thread numbers now return 404 instead of sinatra's 500,

closing the issue.
