### ISSUE TITLE
Shouldn't the Content-Type of the API response be application/json?

### ISSUE THREAD

**Issue by Adorable-Catgirl** [dangeru/awoo#27]
The response is text/html but the data is JSON.
![image](https://user-images.githubusercontent.com/30084950/32753772-21c48456-c89c-11e7-80ce-89770a7edd6c.png)

**Comment by nilesr** [comment]
no fuck off

**Comment by puzzl3** [comment]
well you received your answer
"no fuck off" sums it up nicely
closing this

**Comment by puzzl3** [comment]
wait it should wtf lain

**Comment by naomiEve** [comment]
text/html or not
we still return JSON

**Comment by Adorable-Catgirl** [comment]
this comes from the person who said my IP ban HTTP code was wrong?

**Comment by naomiEve** [comment]
what ip ban code

**Comment by puzzl3** [comment]
okay this is going off topic i think
the response is in JSON, returned as data, this can be seen in src/routes/boards.rb from line 466 till around line 500 which can be evidently found by the usage of JSON.dump()

so that resolves things i think

now i'm actually closing this issue and forget about it

**Comment by naomiEve** [comment]
we always returned JSON
he's talking about the `Content-Type` headers when passing the json to the client, which 90% of users don't care about

**Comment by nilesr** [comment]
@puzzl3 I didn't close it because it is actually something that should be fixed

**Comment by naomiEve** [comment]
fixed in commit https://github.com/dangeru/awoo/commit/d8cf6369215bd0598eb361f586d137e1e1929feb
