### ISSUE TITLE
Mysql2::Error at /post

### ISSUE THREAD

**Issue by fixator10** [dangeru/awoo#28]
Mysql2 returns error on creating thread if emoji 🕹 is in content.

![screenshot](https://Moeka.is-a-good-waifu.com/e45092.png)

(Found at [dangeru.us/test](https://dangeru.us/test))

**Comment by naomiEve** [comment]
change your db charset and collation to utf8mb4
https://stackoverflow.com/questions/6115612/how-to-convert-an-entire-mysql-database-characterset-and-collation-to-utf-8

**Comment by naomiEve** [comment]
oh and the reason why it doesn't work on /u/ is due to a misconfigured db. but i'm too afraid to touch it since whenever i tried doing that it just broke

**Comment by fixator10** [comment]
The problem is this happened on https://dangeru.us/, so...

**Comment by naomiEve** [comment]
i mean, it's properly configured for unicode, but only emojis break it for some reason; it worked fine on lain's test bench for some reason.
