### ISSUE TITLE
Mysql error while trying to view a thread

### ISSUE THREAD

**Issue by dogamak** [dangeru/awoo#30]
So this surfaced while browsing /v/.
[Error page](https://u.teknik.io/3hKjv.htm)

**Comment by naomiEve** [comment]
this is normal, it happens when too many mysql commands are running at once. it's all purely because of ruby.
a refresh or two usually help it

**Comment by dogamak** [comment]
This caused me no trouble and was resolved with one refresh, I just thought you might be interested.
This can be closed if this is a known thing.

**Comment by nilesr** [comment]
Thanks for the report
