### ISSUE TITLE
Sub domain

### ISSUE THREAD

**Issue by robotrono** [dangeru/awoo#34]
Hi, I have installed Vesta CP (CP Webserver), how is possible to install awoo in a sub domain? Its my first time in Ruby.

**Comment by nilesr** [comment]
It looks like Vesta CP uses apache and nginx as its web frontend. Both of these can be configured to reverse proxy to a different port based on subdomain, so for example you could run awoo on port 8080 and have your regular web server forward requests that it recieves to that subdomain to awoo. I don't know how to configure that from Vesta CP, I would suggest just directly modifying the config files for your webserver.

**Comment by robotrono** [comment]
Thanks for the response, I'll try to read the vesta docs.

**Comment by Fieel** [comment]
@nilesr is it possible to set up unicorn to run sinatra with a web socket so i can use nginx listening on said socket instead of the automatic "rerun" server on localhost:8080 that's automatically set up in this repo?

I'm sorry for the noob question, i'm also new to ruby, learning it building this project.

**Comment by nilesr** [comment]
You can certainty do that, not using web sockets but that's just
terminology. Nginx supports that (reverse proxy), and you don't need
unicorn, you can do it directly from nginx to sinatra

**Comment by nilesr** [comment]
Sinatra runs it's own web server, on port 8080. If it's running locally you
should be able to connect to it on localhosr:8080. The port is configurable
in config.json. Rerun just restarts the server if you change the code, we
are abusing it to restart the server if a password reset happens. Nginx
jugar needs to be configured to act as a reverse proxy to port 8080 when it
gets a connection on your subdomain.

**Comment by Fieel** [comment]
I have problems with permissions and how the repo has been set up to work with the Makefile :(.

When the service listed in the Makefile runs on its own my connections get rejected by NGINX (which is simply proxying 127.0.0.1:8080) for some reason _(nginx errorl log)_:

![image](https://user-images.githubusercontent.com/11167635/50426190-98e0fe80-0887-11e9-90c0-8d72ad672bea.png)

If i manually run the following command (which i'm having an hard time understanding):

`sudo /usr/bin/env rerun -b -p _watch rackup`

the server actually starts and i can reach 127.0.0.1:8080 through nginx:

<img width="558" alt="awoo-problem3" src="https://user-images.githubusercontent.com/11167635/50426212-07be5780-0888-11e9-8439-869c88d73bec.PNG">

At this point, i can hit awo.fieel.space (my domain) and reach the sinatra application, i get an exception though:

<img width="757" alt="awoo-problem4" src="https://user-images.githubusercontent.com/11167635/50426219-523fd400-0888-11e9-8ce6-a1d9e9278e56.PNG">

I didn't touch the source code yet - at this point i have no idea how i should approach the problem.

I come from a dotnet/angular/react environemnt, that might explain why i'm having an hard time understanding all of this?

**Comment by nilesr** [comment]
Aah, the archived posts table is empty. This is a bug we never noticed
because I only used this on my laptop and existing servers. It should still
work to go to a board like /test/
