### ISSUE TITLE
Captcha word list missing from repo

### ISSUE THREAD

**Issue by Fieel** [dangeru/awoo#36]
Hello, 

When trying to start the application in my "testing" home web server following the instructions in the README.md i get this error:

<img width="783" alt="awoo-bug" src="https://user-images.githubusercontent.com/11167635/50425929-279e4d00-0881-11e9-8497-2e2c5ec30d62.PNG">

From what i understand the captcha uses a list of words readen from a file /usr/share/dict/words which of course i don't have: i simply cloned your repo and that's it.

Not sure if it's an issue or not, feel free to close if it isn't.

**Comment by nilesr** [comment]
Merry Christmas. What distro? You may have to install a wordlist or
dictionary package, it was already installed on my computer. On
Debian/Ubuntu you can determine the right package with apt-file, on arch
with pkgfile. You can also change the path to point to your own wordlist
